{
  description = "Bazel 9 Nix Dev Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            bazelisk
            buildifier
            llvmPackages.clang-tools
            git
            libxml2.out
            openjdk25
            python3
            zlib
            llvmPackages.lld
            nixd
            go
            gopls
            rustc
            cargo
            delve
            llvmPackages.lldb
          ];

          shellHook = ''
            # Create a libxml2.so.2 symlink for LLVM ld.lld compatibility
            mkdir -p tools/sysroot/libxml2_compat
            ln -sf ${pkgs.libxml2.out}/lib/libxml2.so tools/sysroot/libxml2_compat/libxml2.so.2

            # Generate the Linux x86-64 sysroot if not present
            if [ ! -d tools/sysroot/linux-x86_64 ]; then
              ./tools/sysroot/generate.sh
            fi

            # Export JAVA_HOME pointing to openjdk25
            if [ -d "${pkgs.openjdk25}/Library/Java/JavaVirtualMachines" ]; then
              export JAVA_HOME=$(find "${pkgs.openjdk25}" -name Home -type d | head -n 1)
            elif [ -d "${pkgs.openjdk25}/lib/openjdk" ]; then
              export JAVA_HOME=${pkgs.openjdk25}/lib/openjdk
            else
              export JAVA_HOME=${pkgs.openjdk25}
            fi

            # Dynamically symlink kls-classpath to tools/kls-classpath
            ln -sf tools/kls-classpath kls-classpath



            # Set BAZEL_SH for Bazel target execution on NixOS
            export BAZEL_SH=${pkgs.bash}/bin/bash

            # Write machine-local settings to a gitignored file
            {
              echo "# Generated by flake.nix shellHook"
              ${pkgs.lib.optionalString pkgs.stdenv.isDarwin ''
                echo "build --config=macos"
                echo "build:macos --cxxopt=-cxx-isystem${pkgs.stdenv.cc.libcxx}/include/c++/v1"
                echo "build:macos --host_cxxopt=-cxx-isystem${pkgs.stdenv.cc.libcxx}/include/c++/v1"
                echo "build:macos --linkopt=-L${pkgs.stdenv.cc.libcxx}/lib"
                echo "build:macos --host_linkopt=-L${pkgs.stdenv.cc.libcxx}/lib"
              ''}
              ${pkgs.lib.optionalString pkgs.stdenv.isLinux ''
                echo "build --config=linux"
                echo "build:linux --action_env=LD_LIBRARY_PATH=$PWD/tools/sysroot/libxml2_compat"
                echo "build:linux --action_env=NIX_LDFLAGS"
                echo "build:linux --action_env=NIX_CFLAGS_COMPILE"
                echo "build:linux --action_env=PATH"
                echo "build --shell_executable=${pkgs.bash}/bin/bash"
                echo "build:linux --@rules_rust//rust/settings:extra_rustc_env=PATH=$PATH,LD_LIBRARY_PATH=$PWD/tools/sysroot/libxml2_compat,LIBRARY_PATH=${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.stdenv.cc.cc}/lib/gcc/${pkgs.stdenv.hostPlatform.config}/${pkgs.stdenv.cc.cc.version}"
                echo "build:linux --@rules_rust//rust/settings:extra_exec_rustc_env=PATH=$PATH,LD_LIBRARY_PATH=$PWD/tools/sysroot/libxml2_compat,LIBRARY_PATH=${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.stdenv.cc.cc}/lib/gcc/${pkgs.stdenv.hostPlatform.config}/${pkgs.stdenv.cc.cc.version}"
              ''}
            } > .bazelrc.user
          '';
        };
      }
    );
}
