{
  description = "Bazel 9 Nix Dev Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            bazelisk
            buildifier
            llvmPackages.clang-tools
            git
            libxml2.out
          ];

          shellHook = ''
            # Create a libxml2.so.2 symlink for LLVM ld.lld compatibility
            mkdir -p sysroot/libxml2_compat
            ln -sf ${pkgs.libxml2.out}/lib/libxml2.so sysroot/libxml2_compat/libxml2.so.2

            # Set BAZEL_SH for Bazel target execution on NixOS
            export BAZEL_SH=${pkgs.bash}/bin/bash

            # Write machine-local settings to a gitignored file
            {
              echo "# Generated by flake.nix shellHook"
              ${pkgs.lib.optionalString pkgs.stdenv.isDarwin ''
                echo "build --config=macos"
              ''}
              ${pkgs.lib.optionalString pkgs.stdenv.isLinux ''
                echo "build --config=linux"
                echo "build --sandbox_add_mount_pair=${pkgs.bash}/bin/bash:/bin/bash"
                echo "build:linux --action_env=LD_LIBRARY_PATH=$PWD/sysroot/libxml2_compat"
                echo "build --shell_executable=${pkgs.bash}/bin/bash"
              ''}
            } > .bazelrc.user
          '';
        };
      }
    );
}
