# Quarkus Application Configuration
quarkus.application.name=quarkus-app
platform.quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.log.level=INFO
quarkus.native.enabled=true
quarkus.native.sources-only=true
