load("@rules_java//java:defs.bzl", "JavaInfo")

KlsInfo = provider(
    doc = "Information about transitive compile-time and source JARs for KLS",
    fields = {
        "transitive_jars": "depset of structs containing class_jar and source_jar"
    }
)

def _kls_aspect_impl(target, ctx):
    direct_jars = []
    
    # If the target provides JavaInfo, extract its output JARs
    if JavaInfo in target:
        for jar in target[JavaInfo].outputs.jars:
            class_jar = jar.compile_jar if jar.compile_jar else jar.class_jar
            source_jar = jar.source_jar if jar.source_jar else None
            if class_jar:
                direct_jars.append(struct(
                    class_jar = class_jar,
                    source_jar = source_jar,
                ))
            
    transitive_jars = []
    # Propagate the aspect along dependencies and extensions attributes
    for attr_name in ["deps", "runtime_deps", "exports", "runtime_extensions", "deployment_extensions"]:
        if hasattr(ctx.rule.attr, attr_name):
            val = getattr(ctx.rule.attr, attr_name)
            if type(val) == "list":
                for dep in val:
                    if KlsInfo in dep:
                        transitive_jars.append(dep[KlsInfo].transitive_jars)
            elif val and KlsInfo in val:
                transitive_jars.append(val[KlsInfo].transitive_jars)
                
    return [
        KlsInfo(
            transitive_jars = depset(
                direct = direct_jars,
                transitive = transitive_jars,
            )
        )
    ]

kls_aspect = aspect(
    implementation = _kls_aspect_impl,
    attr_aspects = ["deps", "runtime_deps", "exports", "runtime_extensions", "deployment_extensions"],
)

_CLASSPATH_PRINT_TEMPLATE = """#!/usr/bin/env python3
# Generated by kls_classpath rule
import os
import subprocess
import sys

def main():
    workspace_root = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if not workspace_root:
        workspace_root = os.getcwd()

    # Find the Bazel execution root
    try:
        execroot = subprocess.check_output(["bazelisk", "info", "execution_root"], text=True, cwd=workspace_root).strip()
    except subprocess.CalledProcessError:
        execroot = os.path.join(workspace_root, "bazel-bazel")

    # Find relative compile.txt path in runfiles
    paths_name = "{relative_paths_name}"
    runfiles_dir = os.environ.get("RUNFILES_DIR")
    paths_file = None
    if runfiles_dir:
        for root, dirs, files in os.walk(runfiles_dir):
            if paths_name in files:
                paths_file = os.path.join(root, paths_name)
                break
    
    if not paths_file:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        paths_file = os.path.join(script_dir, paths_name)

    if os.path.exists(paths_file):
        with open(paths_file, "r") as f:
            for line in f:
                path = line.strip()
                if path:
                    print(os.path.join(execroot, path))

if __name__ == "__main__":
    main()
"""

def _kls_classpath_impl(ctx):
    transitive_jars = []
    for dep in ctx.attr.targets:
        if KlsInfo in dep:
            transitive_jars.append(dep[KlsInfo].transitive_jars)
            
    all_jars = depset(transitive = transitive_jars)
    
    compile_paths = []
    source_paths = []
    json_entries = []
    
    # Deduplicate by class_jar path to avoid duplicates
    seen_classes = {}
    
    for item in all_jars.to_list():
        class_path = item.class_jar.path if item.class_jar else ""
        source_path = item.source_jar.path if item.source_jar else ""
        
        if class_path and class_path not in seen_classes:
            seen_classes[class_path] = True
            compile_paths.append(class_path)
            
            entry = {
                "class_jar": class_path,
            }
            if source_path:
                source_paths.append(source_path)
                entry["source_jar"] = source_path
            json_entries.append(entry)
            
    # Output file containing newline-separated compile JAR paths
    compile_file = ctx.actions.declare_file(ctx.label.name + "_compile.txt")
    ctx.actions.write(
        output = compile_file,
        content = "\n".join(compile_paths) + "\n",
    )
    
    # Output file containing structured mapping of class to source jars
    json_file = ctx.actions.declare_file(ctx.label.name + ".json")
    ctx.actions.write(
        output = json_file,
        content = json.encode(json_entries) + "\n",
    )
    
    # Generate the executable Python script
    executable = ctx.actions.declare_file(ctx.label.name + ".py")
    ctx.actions.write(
        output = executable,
        content = _CLASSPATH_PRINT_TEMPLATE.format(
            relative_paths_name = compile_file.basename,
        ),
        is_executable = True,
    )
    
    return [
        DefaultInfo(
            executable = executable,
            runfiles = ctx.runfiles(files = [compile_file, json_file]),
        )
    ]

kls_classpath = rule(
    implementation = _kls_classpath_impl,
    attrs = {
        "targets": attr.label_list(
            aspects = [kls_aspect],
        ),
    },
    executable = True,
)

_PYTHON_SCRIPT_TEMPLATE = """#!/usr/bin/env python3
# Generated by kls_workspace rule
import os
import json
import subprocess
import sys

def main():
    workspace_root = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if not workspace_root:
        print("Error: BUILD_WORKSPACE_DIRECTORY environment variable not set. Run this target via 'bazel run'.", file=sys.stderr)
        sys.exit(1)

    # Find the Bazel execution root
    try:
        execroot = subprocess.check_output(["bazelisk", "info", "execution_root"], text=True, cwd=workspace_root).strip()
    except subprocess.CalledProcessError:
        execroot = os.path.join(workspace_root, "bazel-bazel")

    # Find relative JSON path in runfiles
    json_name = "{relative_json_name}"
    runfiles_dir = os.environ.get("RUNFILES_DIR")
    if runfiles_dir:
        candidate1 = os.path.join(runfiles_dir, "bazel_project", json_name)
        candidate2 = os.path.join(runfiles_dir, "_main", json_name)
        if os.path.exists(candidate1):
            relative_json_path = candidate1
        elif os.path.exists(candidate2):
            relative_json_path = candidate2
        else:
            relative_json_path = None
            for root, dirs, files in os.walk(runfiles_dir):
                if json_name in files:
                    relative_json_path = os.path.join(root, json_name)
                    break
            if not relative_json_path:
                print(f"Error: Could not find {{json_name}} in runfiles", file=sys.stderr)
                sys.exit(1)
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        relative_json_path = os.path.join(script_dir, json_name)

    with open(relative_json_path, "r") as f:
        classpath_data = json.load(f)

    print(f"Found {{len(classpath_data)}} class JAR dependencies.")

    libraries = []
    dependencies = [
        {{"type": "inheritedSdk"}},
        {{"type": "moduleSource"}}
    ]

    for idx, entry in enumerate(classpath_data):
        class_jar = os.path.join(execroot, entry["class_jar"])
        if not os.path.exists(class_jar):
            continue

        lib_name = f"library_{{idx}}_{{os.path.basename(class_jar)}}"
        roots = [
            {{
                "path": class_jar,
                "type": "CLASSES",
                "inclusionOptions": "root_itself"
            }}
        ]

        if "source_jar" in entry:
            source_jar = os.path.join(execroot, entry["source_jar"])
            if os.path.exists(source_jar):
                roots.append({{
                    "path": source_jar,
                    "type": "SOURCES",
                    "inclusionOptions": "root_itself"
                }})

        lib_data = {{
            "name": lib_name,
            "type": None,
            "level": "project",
            "roots": roots,
            "excludedRoots": []
        }}
        libraries.append(lib_data)

        dep_data = {{
            "type": "library",
            "name": lib_name,
            "scope": "compile",
            "isExported": False
        }}
        dependencies.append(dep_data)

    source_roots = []
    java_src = os.path.join(workspace_root, "src/main/java/src")
    if os.path.exists(java_src):
        source_roots.append({{
            "path": java_src,
            "type": "java-source"
        }})

    kotlin_src = os.path.join(workspace_root, "src/main/kotlin/src")
    if os.path.exists(kotlin_src):
        source_roots.append({{
            "path": kotlin_src,
            "type": "kotlin-source"
        }})

    module = {{
        "name": "bazel-module",
        "type": "JAVA_MODULE",
        "dependencies": dependencies,
        "contentRoots": [
            {{
                "path": workspace_root,
                "excludedPatterns": [],
                "excludedUrls": [],
                "sourceRoots": source_roots
            }}
        ],
        "facets": []
    }}

    workspace_data = {{
        "modules": [module],
        "libraries": libraries
    }}

    output_file = os.path.join(workspace_root, "workspace.json")
    with open(output_file, "w") as f:
        json.dump(workspace_data, f, indent=4)

    print(f"Successfully generated {{output_file}} with {{len(libraries)}} libraries.")

if __name__ == "__main__":
    main()
"""

def _kls_workspace_impl(ctx):
    transitive_jars = []
    for dep in ctx.attr.targets:
        if KlsInfo in dep:
            transitive_jars.append(dep[KlsInfo].transitive_jars)
            
    all_jars = depset(transitive = transitive_jars)
    
    json_entries = []
    seen_classes = {}
    
    for item in all_jars.to_list():
        class_path = item.class_jar.path if item.class_jar else ""
        source_path = item.source_jar.path if item.source_jar else ""
        
        if class_path and class_path not in seen_classes:
            seen_classes[class_path] = True
            entry = {
                "class_jar": class_path,
            }
            if source_path:
                entry["source_jar"] = source_path
            json_entries.append(entry)
            
    # Output file containing structured mapping of class to source jars
    json_file = ctx.actions.declare_file(ctx.label.name + "_classpath.json")
    ctx.actions.write(
        output = json_file,
        content = json.encode(json_entries) + "\n",
    )
    
    # Generate the executable Python script
    executable = ctx.actions.declare_file(ctx.label.name + ".py")
    ctx.actions.write(
        output = executable,
        content = _PYTHON_SCRIPT_TEMPLATE.format(
            relative_json_name = json_file.basename,
        ),
        is_executable = True,
    )
    
    return [
        DefaultInfo(
            executable = executable,
            runfiles = ctx.runfiles(files = [json_file]),
        )
    ]

kls_workspace = rule(
    implementation = _kls_workspace_impl,
    attrs = {
        "targets": attr.label_list(
            aspects = [kls_aspect],
        ),
    },
    executable = True,
)

